### ISSUE TITLE
libcurl disappeared

### ISSUE THREAD

**Issue by doughsay** [docker-library/ruby#126]
I'm debugging a rather gnarly issue with one of our images, and I'm hoping maybe someone here can shed some light on something for me.

For reference, here's my Dockerfile:
```Dockerfile
FROM ruby:2.1-alpine

ENV RUNTIME_PACKAGES libxml2 libxslt tzdata libstdc++ nodejs openjdk8-jre
ENV BUILD_PACKAGES ruby-dev build-base libxml2-dev libxslt-dev

RUN apk add --update --no-cache $RUNTIME_PACKAGES $BUILD_PACKAGES

RUN mkdir /usr/app
WORKDIR /usr/app

COPY Gemfile /usr/app/
COPY Gemfile.lock /usr/app/
COPY vendor /usr/app/vendor

RUN bundle config build.nokogiri --use-system-libraries
RUN bundle install --local

RUN apk del $BUILD_PACKAGES

COPY . /usr/app

RUN bundle exec rake assets:precompile
```

On April 26th, we successfully built this image using ruby:2.1-alpine (f0c3023eb6a3).  The next day, April 27th, our CI pulled a newer version of ruby:2.1-alpine (188ff54ddb9f).  Builds then started failing (in the asset compile step) with the error:

```
LoadError: Could not open library 'libcurl': Error loading shared library libcurl: No such file or directory.
Could not open library 'libcurl.so': Error loading shared library libcurl.so: No such file or directory.
Could not open library 'libcurl.so.4': Error loading shared library libcurl.so.4: No such file or directory.
Could not open library 'libcurl.so.4.so': Error loading shared library libcurl.so.4.so: No such file or directory
```

The fix is easy enough; just add `libcurl` to the RUNTIME_PACKAGES variable in my Dockerfile.  But we're seeing other strange behavior and I'm wondering if it has something to do with anything else that may have changed between those two image versions.

Can anyone explain why it worked fine in the earlier version of the image, and stopped working in the next?  From what I see in your commit history the ONLY thing you keep updating is bundler and rubygems, which I can't imagine has any affect on this stuff...

Thanks for any help that you could provide.

**Comment by tianon** [comment]
Sorry for the delay.

As far as I can tell looking through the history of https://github.com/docker-library/repo-info/tree/master/repos/ruby, an image with an ID of `f0c3023eb6a3` doesn't seem to have existed any time between now and 2015 (although `188ff54ddb9f` does, so that's at least somewhat comforting).

As for changes I can find that likely caused this, I think https://github.com/docker-library/ruby/pull/88/files is probably the most likely culprit (switching from `curl` to `wget` for downloading Ruby sources), although that was merged Sep 20, 2016, so the only thing I can figure is that maybe your CI hadn't been pulling an updated base image for a long time, and on Apr 27, 2017 finally did?

Looking through https://github.com/docker-library/repo-info/commits/master/repos/ruby/local/2.1-alpine.md, there doesn't seem to have been _any_ changes to `ruby:2.1-alpine` from March 31st until May 5th (https://github.com/docker-library/repo-info/commit/db82ed506d2c9e83de264ca17d08131b2efa4495#diff-a399bafdb118e811887fadb913b3f1f8 -- which clearly shows the `188ff54ddb9f` image ID you've referenced).

https://github.com/docker-library/repo-info/commit/ce8ea9c1dcbbfefcd97671535a6786b77ebb4e19#diff-a399bafdb118e811887fadb913b3f1f8 is the point where `188ff54ddb9f` was created, which is March 31st.

Hope that helps!
