### ISSUE TITLE
Support for nodejs

### ISSUE THREAD

**Issue by fabn** [docker-library/ruby#137]
Now that rails added official support for node/yarn with webpacker gem it would be nice to have an image variant that also provide these tools.

What do you think?

**Comment by tianon** [comment]
Since Node.js is not required/necessary for stock Ruby, I don't think it makes a lot of sense to include it by default in this image (since then everyone pays the size increase cost instead of just the subset of users who require Node.js in addition to Ruby).

As a point of interest, the deprecated `rails` image included the `nodejs` package: https://github.com/docker-library/rails/blob/e4387022ba045745cc26cafbb77b5c910d7e1964/Dockerfile#L4 (which is a good example to show how simple it is to add this to your own image)
