### ISSUE TITLE
Security flaw in latest rubies

### ISSUE THREAD

**Issue by icarito** [docker-library/ruby#150]
Vulnerability found. How to patch apps running from hub images? Thanks in advance!
https://www.ruby-lang.org/en/news/2017/08/29/multiple-vulnerabilities-in-rubygems/

**Comment by yosifkit** [comment]
We install the latest version of rubygems in the image and update it automatically. It was bumped to the fixed version with https://github.com/docker-library/ruby/commit/d2a85bf5a3799c0592140ff66b269c823b813998 and then pushed to the Docker Hub with https://github.com/docker-library/official-images/pull/3378.  To update any images you build, just pull the new image and rebuild yours.  I would suggest doing this in a CI pipeline so that tests can be run on your new images prior to deploying to production.
