### ISSUE TITLE
Support for rubygem mirrors

### ISSUE THREAD

**Issue by davidvanlaatum** [docker-library/ruby#207]
Would be really nice to be able to pass in an environment variable and have it configure gem and bundle to use that for all downloads

**Comment by yosifkit** [comment]
I believe that would be just be a `RUN` line with `gem sources --add http://gems.example.com:9292` and similarly for bundle: `bundle config mirror.https://rubygems.org http://gems.example.com:9292`.

It can also be in the Gemfile:
```ruby
source "http://gems.example.com:9292"
```

I don't see this as something we could accomplish in a custom docker-entrypoint since it would be needed during `docker build` in a random `RUN` line and not once the image is built and a container is created.

Sources:
- http://guides.rubygems.org/run-your-own-gem-server/
- https://bundler.io/v1.16/bundle_config.html#MIRRORS-OF-GEM-SOURCES
