### ISSUE TITLE
No Ruby 2.6.1 image available

### ISSUE THREAD

**Issue by morgoth** [docker-library/ruby#263]
Looks like it was added to repo https://github.com/docker-library/ruby/commit/3e2c9f3f3c34820dd38212f68c1d5f0300264711 but image is still not available on docker registry.

Is it because of some delay in automatic workflow or is it there actually some issue with pushing it?

**Comment by mikegee** [comment]
I think the next step is a PR to https://github.com/docker-library/official-images. @tianon updated the Ruby images recently in https://github.com/docker-library/official-images/pull/5278, so maybe that part is not automated.

**Comment by yosifkit** [comment]
https://github.com/docker-library/ruby/tree/6301325faf42a96b1fd1be5650e451cae31e0728#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

The process to actually get from the auto updates in this repo to built images on the hub is not automated. We regularly do PRs to official-images to do a final review of changes, whether the changes were made by bots or PRs, and once merged, automation takes over to build all the versions and OS variations across the seven architectures. We'll probably have one up later today especially since #262 was merged.
