### ISSUE TITLE
Continue support for Debian Jessie

### ISSUE THREAD

**Issue by panthomakos** [docker-library/ruby#292]
There are a few changes in the Debian Jessie to Buster upgrade that have caused issues for Dockerfiles based on these images. For example, the default gcc compiler changes from 7 to 8 (this causes issues for building some packages from source like passenger/nginx depending on the version, and causes issues for installing some gems like `zookeeper`), the mysql-client-5.5 library is no longer compatible and requires a change to mariadb, etc. Is it possible to continue to support a Debian Jessie flavor of these images? I realize it is no longer the default for Debian, so using a separate tag (`VERSION-jessie`) would be totally fine.

**Comment by yosifkit** [comment]
Some of the images should still have a `-jessie` tag that is available to pull (see https://hub.docker.com/_/ruby?tab=tags), but we only actively maintain ruby on the last 1 or 2 OS releases in order to lessen the load on our build infrastructure.

It should also be noted that Debian Jessie will be end of life in 2020 (https://wiki.debian.org/LTS) and if you are going to stay on Jessie, you may want to have your company support those still working on it (https://wiki.debian.org/LTS/Funding). You are welcome to take our Jessie Dockerfile and adapt it for your needs :smile:.
