### ISSUE TITLE
Inconsistent behaviour with Array#select

### ISSUE THREAD

**Issue by sarat1669** [docker-library/ruby#293]
`Array#select` returns an Array on first invocation, but returns `nil` for all the subsequent invocations.

I am using ruby 2.5.1 in docker.

Code:
```ruby
results = Spree::Product.where(id: product_ids).select(&:is_orderable?)
```

Natively it was working fine. This issue is happening only when I am using docker.
Upgrading the ruby image to 2.6.3 seems to fix the issue.

**Comment by wglambert** [comment]
When you tested this outside of Docker was that on the same 2.5.1 version?

**Comment by sarat1669** [comment]
Yes

**Comment by tianon** [comment]
I can't reproduce on the latest Ruby 2.5 release:

```console
$ docker pull ruby:2.5
2.5: Pulling from library/ruby
Digest: sha256:219b0f233f8214793ccc8cdc787224dc6cfb728e98af9ea2c991f23bf1aee1ab
Status: Image is up to date for ruby:2.5

$ docker run -it --rm ruby:2.5
irb(main):001:0> RUBY_VERSION
=> "2.5.5"
irb(main):002:0> a = ["foo", "bar", "baz"]
=> ["foo", "bar", "baz"]
irb(main):003:0> b = a.select { |el| el != "foo" }
=> ["bar", "baz"]
irb(main):004:0> c = b.select { |el| el == "bar" }
=> ["bar"]
```

**Comment by dentarg** [comment]
`Spree::Product` indicates use of a third-party library (https://github.com/spree/spree maybe?). I think a more complete repro needs to back up the claim made here by @sarat1669.

**Comment by sarat1669** [comment]
The codebase which I am working on is private and I cannot share. Will try to replicate the same in a public repo.

**Comment by tianon** [comment]
Given that we can't reproduce, I'm going to close.  I'd recommend trying [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker) for further help narrowing down what's causing this once you've got a small public reproducer so that you can file a PR or issue in the appropriate place (Ruby itself, the Spree project, etc).
