### ISSUE TITLE
Upstream collaboration on Dockerfiles?

### ISSUE THREAD

**Issue by yosifkit** [docker-library/ruby#323]
It seems that upstream is maintaining their [own images](https://hub.docker.com/r/rubylang/ruby/) via https://github.com/ruby/ruby-docker-images.  From their commit history, it looks like they started from our Dockerfiles. Perhaps there is an opportunity to work together?

**Comment by tianon** [comment]
I think that's a great idea -- I hesitate to cold-ping folks from that repository, since I don't know what their interest level is.

@deivid-rodriguez I understand you're probably more on RubyGems than Ruby itself, but perhaps you know some of those folks better than we do and have advice or are willing to start the conversation? :pray: :heart:

**Comment by deivid-rodriguez** [comment]
Sure, I'll ping some people and see what the interest level is. It sounds like a nice idea, indeed!

**Comment by deivid-rodriguez** [comment]
I opened a ticket in the ruby-core repo. I was told to open a ticket in the ruby-core tracker, so I did it: https://bugs.ruby-lang.org/issues/17137.

**Comment by tianon** [comment]
I'm going to go ahead and close this now, but the offer definitely still stands - we'd love even just to have upstream committers commenting on our issues/PRs and providing upstream perspectives (if not outright contributing). :heart:
