### ISSUE TITLE
CVE-2019-19816

### ISSUE THREAD

**Issue by alioualarbi** [docker-library/ruby#328]
Pulling 2.6.6-buster from dockerhub and doing vulnerability scan on GCP container registry.
Which ruby image is pre-built with 4.19.146?

**Comment by yosifkit** [comment]
1. that is a kernel vulnerability (there is no kernel package in the image)
2. the version `4.19.146-1` is the fixed version in Debian Buster: https://security-tracker.debian.org/tracker/CVE-2019-19816

**Comment by tianon** [comment]
See also https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves

**Comment by nealharris** [comment]
I find the way GCR displays kernel vulnerabilities pretty unhelpful. Why does it show kernel vulnerabilities at all? For this issue in particular, GCR says there's a fix available, which is misleading, and doesn't seem to take into account the context of the product: scanning docker images. (There's a fix in the linux kernel, which is what GCR is referring to, but AFAICT, that's not actionable information in this case.)

**Comment by yosifkit** [comment]
To be fair, it is most likely seeing that Debian says that the `linux` source package was vulnerable/fixed in xyz versions. But from that `linux` source package, there are [many](https://packages.debian.org/source/buster/linux) packages that users could install from it. Which includes the kernel (the actual thing the vulnerability applies too), but also things like headers (that don't apply for this vulnerability, as far as I can tell). So GCR would actually have to audit/enhance all of their scanning with this extra knowledge for each individual vulnerability and have instead left that to users to understand if a vulnerability applies to their situation (and sadly, most users do not take the time to understand and just run to the open source maintainers and say "fix this"; https://twitter.com/mjg59/status/1296374298072891393)

**Comment by wglambert** [comment]
Closing since there's nothing actionable for us to do
