### ISSUE TITLE
Vulnerabilities in ruby:2.6-slim-buster

### ISSUE THREAD

**Issue by robbo10** [docker-library/ruby#329]
Scanning `ruby:2.6-slim-buster` with Twistlock reports the following vulnerabilities.
HIGH VULNERABILITIES: 12
MEDIUM VULNERABILITIES: 13

CVE-2019-19770, CVE-2018-12886, CVE-2020-11725, CVE-2019-19814, CVE-2019-19449, CVE-2019-19378, CVE-2019-19377, CVE-2020-25211, CVE-2020-25643, CVE-2020-10663 , CVE-2020-25645, "Private keys stored in image"

We were wondering if there are any plans on upgrading?

Thanks

**Comment by wglambert** [comment]
The only thing to upgrade in `ruby:2.6-slim-buster` is `linux-libc-dev`

<details>
<summary> apt list --upgradeable </summary>

```console
$ docker run -it --rm ruby:2.6-slim-buster bash
Unable to find image 'ruby:2.6-slim-buster' locally
2.6-slim-buster: Pulling from library/ruby
bb79b6b2107f: Pull complete 
e8b853ec9f22: Pull complete 
d21147059b99: Pull complete 
12beaa8b1a46: Pull complete 
7d6e773ea12e: Pull complete 
Digest: sha256:166afca0b27d604b2a810ac86ae43035690c62d93973880dd91c98ec4c5ef1bd
Status: Downloaded newer image for ruby:2.6-slim-buster
root@7c5d888e4c5c:/# apt update
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:2 http://deb.debian.org/debian buster InRelease [121 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [238 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7906 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [7868 B]
Fetched 8391 kB in 2s (4199 kB/s)                         
Reading package lists... Done
Building dependency tree       
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
root@7c5d888e4c5c:/# apt list --upgradeable
Listing... Done
linux-libc-dev/stable 4.19.152-1 amd64 [upgradable from: 4.19.146-1]
N: There is 1 additional version. Please use the '-a' switch to see it
```

</details>

See https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves
And https://github.com/docker-library/postgres/issues/286#issuecomment-302512767 docker-library/openjdk#161, docker-library/openjdk#112, docker-library/postgres#286, docker-library/drupal#84, docker-library/official-images#2740, docker-library/ruby#117, docker-library/ruby#94, docker-library/python#152, docker-library/php#242, docker-library/buildpack-deps#46, docker-library/openjdk#185.

A CVE doesn't imply having an actual vulnerability, and often is even a false positive (given how most distributions handle versioning/security updates in stable releases). If there are actionable items we can resolve, we're happy to do so (and do so actively). We update all Debian based images to include any updates in apt packages at least monthly (we regenerate the base images and then rebuild all dependent images).

Checking those vulnerabilities at https://security-tracker.debian.org 
CVE-2020-25645 - Kernel issue not relevant to Docker containers, it's also unfixed in Buster so there would otherwise be nothing actionable for us to do
CVE-2020-10663 - ruby2.6 is affected through `2.6.5`. This image is on `2.6.6` so it's unaffected
CVE-2020-25643 - Kernel issue
CVE-2020-25211 - Kernel issue
CVE-2019-19377 - Kernel issue
CVE-2019-19378 - Kernel issue
CVE-2019-19449 - Kernel issue
CVE-2019-19814 - Kernel issue
CVE-2020-11725 - Kernel issue
CVE-2018-12886 - Unfixed, but GCC doesn't remain in the image it's removed after installing Ruby https://github.com/docker-library/ruby/blob/5a4e2d8d9fae6681ac3e2344eac547f0e2cdc598/2.6/buster/slim/Dockerfile#L94
CVE-2019-19770 - Kernel issue
