### ISSUE TITLE
Is v2.7.2 shipping v2.7.0 default gems?

### ISSUE THREAD

**Issue by ptemmer** [docker-library/ruby#330]
Not sure if this is a bug, or my bad.
The Ruby 2.7.2 changelog says it includes a fixed version of Webrick (1.6.1) that solves  a vulnerability detected in v1.6.0
https://www.ruby-lang.org/en/news/2020/10/02/ruby-2-7-2-released/

Yet, the ruby-2.7.2 image contains Webrick 1.6.0, moreover I was surprised to see that it seems to ship default gems for 2.7.0, according to the existence of this container path:

/usr/local/lib/ruby/gems/2.7.0

**Comment by yosifkit** [comment]
TLDR; it is patched and not vulnerable.

The image only uses what is bundled in Ruby 2.7.2. From the CVE notes (quoted below) and from the [patch applied](https://github.com/ruby/ruby/commit/828c34e58b63d64558ec0f2d1d7ae401c5e6b21f) it looks like they just applied a backport for any webrick bundled in Ruby (rather than a full version bump).

> Affected versions:
> webrick gem 1.6.0 or prior
> **bundled versions of webrick** in ruby 2.7.1 or prior
> bundled versions of webrick in ruby 2.6.6 or prior
> bundled versions of webrick in ruby 2.5.8 or prior
>
> \- https://www.ruby-lang.org/en/news/2020/09/29/http-request-smuggling-cve-2020-25613/

Dockerfile bits that install Ruby:
https://github.com/docker-library/ruby/blob/5a4e2d8d9fae6681ac3e2344eac547f0e2cdc598/2.7/buster/Dockerfile#L30-L56

**Comment by ptemmer** [comment]
Thank you for the clarification @yosifkit. That explains everything.
A pity they didn't do a version bump, as container image scanning tools keep "detecting" the faulty 1.6.0 webrick.
