### ISSUE TITLE
How to unset environment variables correctly (they're preventing local installs.)

### ISSUE THREAD

**Issue by arianitu** [docker-library/ruby#335]
I notice this image overrides the behaviour of `bundle install` to always install globally and it mentions you can set them to empty string, but it doesn't work.

For example, if you set them all to empty, you get this error on bundle install:

```
The underlying system error is Errno::EISDIR: Is a directory @ io_fread -  /var/project/config
```

This is what I tried:

```
# undo env variables the official ruby docker image sets that prevents local installs
ENV GEM_HOME=""
ENV BUNDLE_SILENCE_ROOT_WARNING=0
ENV BUNDLE_APP_CONFIG=""
ENV BUNDLE_PATH=""
ENV BUNDLE_BIN=""
```

I think the issue with setting `BUNDLE_APP_CONFIG` is that it will use "" which would just use `project/config` instead of `.bundle/config`

I suppose I could set it to `.bundle`, but I am unsure what the correct way to unset these are. I think the project needs updated docs since setting empty string doesn't bring back the default behaviour of bundler.

**Comment by arianitu** [comment]
These seem to work better, but I am unsure if they are correct in bringing back the default behaviour:

```
# undo env variables the official ruby docker image sets that prevents local installs
ENV GEM_HOME=""
ENV BUNDLE_SILENCE_ROOT_WARNING=0
ENV BUNDLE_APP_CONFIG=".bundle"
ENV BUNDLE_PATH="vendor/bundle"
ENV BUNDLE_BIN=false
```

**Comment by tianon** [comment]
It's been a while since we set anything besides just `GEM_HOME`, `BUNDLE_SILENCE_ROOT_WARNING`, and `BUNDLE_APP_CONFIG`:

https://github.com/docker-library/ruby/blob/cf2a6f335a0db67d6d1c957d8d396e5f8ee0cce3/Dockerfile-debian.template#L84-L87

I'm not sure what your end goal is here?  If you're just wanting things to be installed to `.bundle` again, setting `GEM_HOME=.bundle` and `BUNDLE_APP_CONFIG=.bundle` will definitely do that. :sweat_smile:

(Unfortunately, I don't think there's an easy way to "reset" these settings completely, since we don't have a way to actually unset a variable directly in Docker, but you could do something like `sh -c 'unset GEM_HOME BUNDLE_SILENCE_ROOT_WARNING BUNDLE_APP_CONFIG; exec "$@"'` as `SHELL` and/or `ENTRYPOINT`.)

**Comment by arianitu** [comment]
I think that's all I want, just the default behaviour of bundle. I'll set both to `.bundle`, thank you.
