### ISSUE TITLE
2.2.0-slim might be too slim

### ISSUE THREAD

**Issue by nickjj** [docker-library/ruby#34]
I'm running the `2.2.0-slim` tag and the `json 1.8.2` gem won't compile its native extensions without first apt installing `build-essential`. That gem is quite common in rails apps.

Is this something that should be in user land or fixed in slim?

**Comment by md5** [comment]
I think this is expected behavior for `slim`.

In the case of the `json` gem, it can be installed with just `apt-get install -y --no-install-recommends make gcc` since no libraries or headers are required. Depending on how slim you're trying to keep the image, you could either install `make` and `gcc` in their own `RUN` command, making it possible to do a simple `RUN gem install json` on another line, or you could install and remove `make` and `gcc` in the same line that you run `gem install json` (or `bundle install` or whatever).

**Comment by md5** [comment]
I really wish we had the nested builds proposed in docker/docker#7115 to avoid this crap...
