### ISSUE TITLE
Alpine 3.14 support

### ISSUE THREAD

**Issue by SeanLF** [docker-library/ruby#388]
I use ruby `3.1.2-alpine3.14` at my company and wanted to update to the latest version ([3.14.8](https://www.alpinelinux.org/posts/Alpine-3.13.12-3.14.8-3.15.6-3.16.2-released.html)) to get the latest security fixes.

However I noticed that the last time the image was pushed to docker hub was 7 months ago.

Is there a reason why `alpine3.14` support was dropped in #384?

**Comment by tianon** [comment]
We only support two versions of each base distribution (because compiling Ruby from source is relatively heavy, so this is a means to control the sprawl of the supported matrix / load).   As a result, support for Alpine 3.14 was intentionally dropped when we added Alpine 3.16.

That being said, if you still require this, you _should_ be able to clone the repository and adjust either the Alpine 3.16 or 3.15 `Dockerfile` to be `FROM alpine:3.14` and it will likely still work fine (we just unfortunately don't actively support it any longer).

You might _also_ be able to get away with something like `COPY --from=ruby:3.1.2-alpine3.16 /usr/local /usr/local` but I haven't tested (and that might break over time if there are ever incompatibilities in the libraries it invokes).
