### ISSUE TITLE
3.3.0 slim-buster version

### ISSUE THREAD

**Issue by DustinFisher** [docker-library/ruby#436]
Currently there is a [rc](https://hub.docker.com/layers/library/ruby/3.3-rc-slim-buster/images/sha256-d5d4a473581a715417c1ef8e26dedc66fc5220626f4cd4c70948000fef27018f?context=explore) and [preview](https://hub.docker.com/layers/library/ruby/3.3.0-preview1-slim-buster/images/sha256-d5d4a473581a715417c1ef8e26dedc66fc5220626f4cd4c70948000fef27018f?context=explore) image available for Ruby 3.3 with `slim-buster`. Will there be one for the GA release of ruby 3.3?

**Comment by yosifkit** [comment]
Debian Buster based images were dropped during the rc/preview phase when `bookworm` was added: https://github.com/docker-library/ruby/pull/415, so we do not plan to add it back.  We only have capacity to support two OS releases per OS per Ruby version (i.e., two Alpine releases and two Debian releases for each Ruby release, following the two latest OS releases of each).

For example, Debian Bullseye and Bookworm are the current Debian releases and are the active releases for all versions of Ruby that work on them\*. When Debian Trixie comes out, Bullseye would be dropped, and Trixie added to the active Ruby versions.

\* Ruby 3.0 is Buster and Bullseye because it [does not support openssl 3.0](https://github.com/docker-library/ruby/pull/417#discussion_r1190454466) and will be end of life before Debian Trixie comes out.
