### ISSUE TITLE
Since 3.3 the rubygems/indexer.rb lib is missing.

### ISSUE THREAD

**Issue by johansmitsnl** [docker-library/ruby#441]
In all previous versions the file is present. Is this an error?

**Comment by yosifkit** [comment]
We don't do anything to remove this particular dependency. Our [installation process](https://github.com/docker-library/ruby/blob/b45b591a6285cec31be6f08551478e9d38d4fe46/3.3/bookworm/Dockerfile#L59-L94) is fairly straightforward; as far as I know, any rubygems dependency changes would have been changes in Ruby itself (or maybe transitive dependencies of those included gems).

Perhaps something caused by the changes here? https://github.com/ruby/ruby/blob/ruby_3_2/gems/bundled_gems vs https://github.com/ruby/ruby/blob/ruby_3_3/gems/bundled_gems

**Comment by willfish** [comment]
I believe this is fixeddin ruby 3.3.4?

**Comment by deivid-rodriguez** [comment]
Hei, just stumbled upon this. This was a [change](https://github.com/rubygems/rubygems/issues/7426) in RubyGems 3.5. You can get the files back by installing the `rubygems-generate_index` gem I believe.

Not an issue with docker-library, so this seems fine to close.

**Comment by tianon** [comment]
Thanks for the added research/context, @deivid-rodriguez! :heart:
