### ISSUE TITLE
Inline the alpine patch

### ISSUE THREAD

**Issue by Earlopain** [docker-library/ruby#464]
Since I've started building nightly images I've had the build fail two or three times because `bugs.ruby-lang.org` was down (for the alpine patch). Here's such a run from yesterday: https://github.com/docker-ruby-nightly/ruby/actions/runs/9829977556/job/27135651582

> 22.19 wget: server returned error: HTTP/1.1 500 Internal Server Error

Perhaps I build this during an inopportune time, like a maintenance window. Either way, I'd like to inline this patch into the repo here so that this isn't a problem anymore. Theoretically builds here could also run into this, though that probably hasn't happenend yet.

I will make the PR for this, just let me know if it would be accepted.

**Comment by tianon** [comment]
That patch is a bit larger than I'd like to see inlined, if we can avoid it.  If we were to run into this, it wouldn't be a big hassle for us because we'd automatically retry after some period (so we wouldn't even notice unless it was our smoke test CI that ran into it, in which case we'd just "re-run failing jobs" and move on). :sweat_smile: :innocent:

**Comment by Earlopain** [comment]
Fair, was just an idea. It's midly inconvenient at best anyways
