### ISSUE TITLE
Updating linux-libc-dev to 6.1.99-1

### ISSUE THREAD

**Issue by lamroger-nava** [docker-library/ruby#466]
Hi,

We're using vulnerability scanning and this is coming up. 

linux-libc-dev │ CVE-2023-52760 │ HIGH     │ fixed  │ 6.1.94-1          │ 6.1.99-1      │ kernel: gfs2: Fix slab-use-after-free in gfs2_qd_dealloc 

Wondering if we could get a patch for it or see if upstream debian:bookworm-slim updates it. Thanks!

Specifically we're looking at https://hub.docker.com/layers/library/ruby/3.3.4-slim/images/sha256-8c898a6c45618c25e541a1a835e1d12107618c2741c4157f8760d418e9c458b9?context=explore

**Comment by tianon** [comment]
> In the Linux kernel, ...

For use in containers, this is the most important clue here -- there's not typically a kernel in container images, and even if there were, it isn't used (since the way containers work necessitate using the kernel of the host).  In other words, this vulnerability does _not_ actually apply to `linux-libc-dev` (since it does not include/contain the kernel itself).

See also https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves

(For what it's worth, https://github.com/docker-library/official-images/pull/17227 should also trigger a rebuild which should also resolve this false-positive.)

**Comment by lamroger-nava** [comment]
Thanks for the info!
