### ISSUE TITLE
CVE-2023-31484 libperl5.36

### ISSUE THREAD

**Issue by ayush2629** [docker-library/ruby#481]
base image: ruby:3.2.6-slim-bookworm

debian:bookworm:libperl5.36
Version5.36.0-7+deb12u1
Fix version5.38.2-2

i am using arm64 architecture. how to resolve this debian package issue as tried installing different version of ruby alongside

**Comment by yosifkit** [comment]
`libperl` is from Debian packages and from the [Debian Security Tracker](https://security-tracker.debian.org/tracker/CVE-2023-31484), there is no fix available on Debian Bookworm: `<no-dsa> (Minor issue)`.

It is very common for these minor CVEs to remain unfixed in any Linux distribution. Commercial distributions often mark them as "won't fix" (which CVE scanners often use as signal to filter it out for that distro). Because Debian is community run, it isn't marked as "won't fix", just "no dsa" (no Debian Security Advisory). This means that the (volunteer) Debian Security Team has deemed it minor enough that they won't work on a backport fix. But because any Debian Developer could feel strongly about a specific fix and provide a backported patch, it isn't "won't fix".

See also https://github.com/docker-library/faq/blob/efbfa298bad3d9b860babe7deafdb3b3d25a6b0b/README.md#why-does-my-security-scanner-show-that-an-image-has-cves
