### ISSUE TITLE
Issue with installing nokogiri

### ISSUE THREAD

**Issue by tobstarr** [docker-library/ruby#55]
As described in https://github.com/sparklemotion/nokogiri/issues/1370 there seems to be an issue with the rubygems upgrade to 2.5.0 and installing nokogiri with the overlay driver.

As it seems more a docker issue I would recommend to downgrade to rubygems 2.4.8 for the time being as this will probably affect quite a lot build setups.

The quick fix we are currently doing is run `gem update --system '2.4.8'` in our Dockerfile.

**Comment by wyaeld** [comment]
@yosifkit would you consider reverting https://github.com/docker-library/ruby/commit/74ee8aec9c17ea2134db8a8ef199cf092c829576 until this is resolved

**Comment by tianon** [comment]
Since `nokogiri` is the only gem we've seen actually affected, I'm not keen on downgrading rubygems just for the overlayfs+nokogiri compilation combination.  It sounds like the bug is probably something in `rubygems` (or perhaps in the way `rubygems` interacts with the `nokogiri` build bits), and some brave soul needs to do a bisect from rubygems 2.4.8 to 2.5.0 and figure out what happened so this can either get fixed in rubygems or be narrowed down to something in nokogiri specifically for sure so it can be fixed properly.

**Comment by wyaeld** [comment]
https://github.com/docker/docker/issues/18578 is related

**Comment by tianon** [comment]
With more recent Docker, Ruby, Kernel, etc, this appears to be fixed. :+1:

```console
$ docker info
...
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
...
Kernel Version: 4.6.5-gentoo
Operating System: Gentoo/Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 30.88 GiB
...
$ docker run -it --rm ruby gem install nokogiri
Fetching: mini_portile2-2.1.0.gem (100%)
Successfully installed mini_portile2-2.1.0
Fetching: pkg-config-1.1.7.gem (100%)
Successfully installed pkg-config-1.1.7
Fetching: nokogiri-1.6.8.gem (100%)
Building native extensions.  This could take a while...
Successfully installed nokogiri-1.6.8
3 gems installed
```
