### ISSUE TITLE
naming the library just as `ruby` gives no idea what is linux distro

### ISSUE THREAD

**Issue by tenzan** [docker-library/ruby#56]
Hello!

Maybe I'm missing, but I naming as `ruby` is really broad name. 
It doesn't give an idea which distro is used at a glance.

Please correct me where I'm missing.

Regards.

**Comment by yosifkit** [comment]
Almost all of the languages in the official images use Debian as per the best practices: https://docs.docker.com/engine/articles/dockerfile_best-practices/#from.  The Dockerfile used to generate each tag is linked at the top of the description on the [Docker Hub](https://hub.docker.com/_/ruby/) in the "Supported tags and respective Dockerfile links" section.  Many of the tags use [buildpack-deps](https://hub.docker.com/_/buildpack-deps/) so that many languages can share layers and make it easy for a user to `gem install` without having to worry about most system libraries.

**Comment by tenzan** [comment]
Thanks for clarification. :)
